version: '3'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=fairshare.company
      - LETSENCRYPT_HOST=fairshare.company
      - LETSENCRYPT_EMAIL=daniel@example.com
    expose:
      - 80
    volumes:
      - ./public:/usr/share/nginx/html
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
networks:
  default:
    external:
      name: nginx-proxy
