name: deploy
on: [push]
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Add to Known Hosts
      run: ssh-keyscan -Ht rsa fairshare.company,${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Deploy with rsync
      run: rsync -avz public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.PUBLIC_DIR }}
